site_name: Benjamin Fernandez Media
site_description: Official blog of Benjamin Fernandez Media
site_author: Benjamin Fernandez
site_url: https://benfernandezmedia.github.io/
repo_url: https://github.com/benfernandezmedia/benfernandezmedia.github.io
theme:
  name: material
  language: en
  favicon: assets/favicon.png
  logo: assets/images/logo.png
  features:
    - content.action.view
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/benfernandezmedia
    - icon: fontawesome/brands/github
      link: https://github.com/benfernandezmedia
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@benfernandezmedia
    - icon: fontawesome/brands/pinterest
      link: https://pinterest.com/benfernandezmedia
markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - footnotes
  - pymdownx.superfences
  - pymdownx.details
  - tables
  - pymdownx.keys:
      separator: +
      strict: false
      camel_case: false
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
copyright: © 2024 Benjamin Fernandez, All rights reserved.
